### PR TITLE
add ability to pull data by bounding box, #4

### PR DESCRIPTION
**Pull request by jsta**
Remaking #9 with a branch so I can make additional PRs

### CODE REVIEW

**Comment by jlisic** [comment]
FYI, still working on this.  I've sent an email to Zhengwei to figure out how to resolve this without killing the CDL server.

**Comment by jlisic** [comment]
Still running into issues with cropscape filling up, let's look into the soap request; it may not entirely match up to the state sets but provides at least an option.

**Comment by jsta** [comment]
Looks like the R syntax for a SOAP request is something like: https://stackoverflow.com/a/27429782/3362993

**Comment by jlisic** [comment]
https://nassgeodata.gmu.edu/CropScapeService/wms_cdlall.cgi?service=wcs&version=1.0.0&request=getcoverage&coverage=cdl_2009&crs=epsg:102004&bbox=130783,2203171,153923,2217961&resx=30&resy=30&format=image/png

Here is the bounding box string for the request.  I need to check what it will do when the underlying layer is not 30m, but this will avoid adding extra files to the cropscape server.  Thanks so much, I'll go through and edit your submission with this change.  Sorry it took so long!

**Comment by jlisic** [comment]
It's in the current repo, just needs testing.

ref cdl_bbox

**Pull request closed without merging**
